.Dd
.Sh Anthony J. Bentley
.Ss About me
I am an electrical engineer from Albuquerque, New Mexico.
Currently I am employed by
.Lk https://www.sandia.gov/ Sandia National Laboratories ,
where I develop hardware testers.
.Pp
My primary interests are:
.Bl -bullet
.It
Embedded systems programming
.It
.Ox ,
Linux, and other UNIX‐like operating systems
.It
Digital hardware and FPGA design
.It
Computer security, forensics, and reverse engineering
.It
Reproducibility, automation, version control, and deployment
.El
.Pp
In my free time I contribute to
.Lk https://www.openbsd.org/ OpenBSD ,
a free, functional, and secure computer operating system.
The bulk of my work there is
.Lk https://man.openbsd.org/packages.7 packaging :
I import external software to the system,
update existing software packages,
and push bugfixes and feature improvements upstream.
.Pp
Occasionally I write about this work for
the
.Ox
Journal:
.Bl -bullet
.It
Taipei, Taiwan, 2019:
.Lk https://undeadly.org/cgi?action=article;sid=20190407152052 \
“Putting the ‘hack’ in ‘hackathon,’ and other stories”
.It
Berlin, Germany, 2017:
.Lk https://undeadly.org/cgi?action=article;sid=20171110124656 \
“On firmware, games, and securing pkg_add runs”
.El
.Ss Other things
.Bl -bullet
.It
.Lk https://photos.roadrunner.page/ Photo gallery
.It
.Lk https://genealogy.roadrunner.page/bentley/ Bentley family genealogy
.It
.Lk https://www.anjbe.name/philosophy/free-culture/ Free Culture
.El
.Pp
GitHub provides
.Lk https://github.com/bentley an overview
of much — though not all — of my open source development work.
.Ss Contact me
The best way to reach me is by email:
.Mt anthony@anjbe.name
.Pp
I have an
.Lk https://www.anjbe.name/id_rsa.pub.txt OpenSSH public key .
